name: helloworld
on: workflow_dispatch
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Build Steps
          run: echo "A demo build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test phase
        run: echo"running test"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy the app
        run: echo "Deploying the app"
        
          
