name: helloworld
on: push
      branches:
        - main
        - deveolp
        -'release/**
    pull_request:
      branches:
        - main   
    
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Build Steps
          run: echo "hello, ${{vars.My_name}}"

          
