name: Github actions Demo
on: push
jobs:
  action-demo:
      runs-on: ubuntu-latest
      steps:
        -name: checkout the code 
         user: actions/checkout@v4
        -name: print index.html file
         run: cat index.html
        

          
